config/routes.rb
Rails.application.routes.draw do
  resources :pins do
    resource :donation, only: [:new]
  end
  resources :users, controllers: "users"
  resources :sessions

  root :to => "pins#index"


  delete "/sign_out" => "sessions#destroy", :as => "sign_out"
  get "/sign_in" => "sessions#new", :as => "sign_in"
  post "/sign_in" => "sessions#create"
  get "/sign_up" => "users#new", :as => "sign_up"
  post "/sign_up" => "users#create"
  get 'donations/new'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  patch "/users/:id(.:format)" => "users#update"

  post "/pins/:pin_id/donations/checkout" => 'donations#checkout', as: "checkout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user
  def self.create_with_omniauth(auth_hash)
    auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :pin

end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  has_many :donations
  mount_uploader :photo, PhotoUploader

  include PgSearch

  pg_search_scope :search_full_text,
  :using => {
    :tsearch => { :any_word => true }
  },
  :against => {
    :title => 'A',
    :description => 'B'
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins, dependent: :destroy
  has_many :donations
  has_many :authentications, dependent: :destroy
  mount_uploader :profpic, ProfpicUploader

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username, :on => :create
  validates_uniqueness_of :username, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = User.create!(username: auth_hash["info"]["name"], password: "PLACEHOLDER", email: auth_hash["extra"]["raw_info"]["email"])
    user.authentications << authentication
    return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def new
  @client_token = Braintree::ClientToken.generate
end

def checkout
  @pin = Pin.find(params[:pin_id])
  standard_amount = 10

  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => standard_amount,
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    @pin.money = @pin.money + standard_amount
    @pin.save
    donation = @pin.donations.new(amount: standard_amount, user_id: current_user.id)
    donation.save


    redirect_to @pin, :flash => { :success => "Transaction successful! Thank you for your support." }
  else
    redirect_to @pin, :flash => { :error => "Transaction failed. Please try again." }
  end
end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :set_auth

  def index
    if params[:query].present?
      @pin = Pin.new
      @pins = Pin.search_full_text(params[:query]).order("created_at DESC")
    else
      @pin = Pin.new
      @pins = Pin.all.order("created_at DESC")
    end
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin posted.' }
        format.json { render :show, status: :created, location: @pin }
        format.js
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end



  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Pin successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  # def upvote
  #   @pin.upvote_by current_user
  #   redirect_to :back
  # end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :photo, :donation)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Signed in"
    else
      render "new", notice: "Invalid email or password"
    end
  end

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      @user = authentication.user
      authentication.update_token(auth_hash)
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Signed in"
    else
      @user = User.create_with_auth_and_hash(authentication, auth_hash)
      redirect_to user_path(@user), notice: "User Profile created"
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Sign up successful"
    else
      render 'new', notice: "Failed to sign up, try again."
    end
  end

  def show
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      @user.save
      redirect_to @user, notice: "User Profile successfully updated"
    else
      render "edit", notice: "Update not successful, try again."
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    redirect_to root_path, notice: "User Profile deleted, please sign up again to be a User."
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :profpic)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/_form.html.erb
<h3 style="text-align:center; margin-top:20px;">Please enter your details</h3>

  <div class="demo-frame">

    <%= form_for :checkout_form, url: checkout_path, html: { id: "cardForm"} do |form| %>

      <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
      <div id="card-number" class="hosted-field"></div>

      <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
      <div id="expiration-date" class="hosted-field"></div>

      <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
      <div id="cvv" class="hosted-field"></div>

      <%= form.hidden_field "payment_method_nonce" %>

      <div class="button-container">
        <%= form.submit "Donate", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
      </div>
    <% end %>
  </div>

<!-- Load the required client component. -->
<script src="https://js.braintreegateway.com/web/3.9.0/js/client.min.js"></script>

<script>
var authorization = '<%= @client_token %>'
var submit = document.querySelector("#submit-payment-btn");
var form = document.querySelector('#cardForm');

braintree.client.create({
// Replace this with your own authorization.
authorization: authorization
}, function (clientErr, clientInstance) {
if (clientErr) {
  // Handle error in client creation
  return;
}

braintree.hostedFields.create({
  client: clientInstance,
  styles: {
    'input': {
      'font-size': '14pt'
    },
    'input.invalid': {
      'color': 'red'
    },
    'input.valid': {
      'color': 'green'
    }
  },
  fields: {
    number: {
      selector: '#card-number',
      placeholder: '4111 1111 1111 1111'
    },
    cvv: {
      selector: '#cvv',
      placeholder: '123'
    },
    expirationDate: {
      selector: '#expiration-date',
      placeholder: '10/2019'
    }
  }
}, function (hostedFieldsErr, hostedFieldsInstance) {
  if (hostedFieldsErr) {
    // Handle error in Hosted Fields creation
    return;
  }

  submit.removeAttribute('disabled');

  form.addEventListener('submit', function (event) {
    event.preventDefault();

    hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
      if (tokenizeErr) {
        // Handle error in Hosted Fields tokenization
        return;
      }

      // Put `payload.nonce` into the `payment-method-nonce` input, and then
      // submit the form. Alternatively, you could send the nonce to your server
      // with AJAX.
      document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
      form.submit();
    });
  }, false);
});
});
</script>

<!-- Load Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.9.0/js/hosted-fields.min.js"></script>

app/views/donations/new.html.erb
<header>
  <h1 style="text-align:center; margin-top:8%;">Payment Gateway</h1>
</header>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinteresting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"    >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  </head>

  <body>
    <div id="flash">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, class: "alert alert-info"%>
      <% end %>
    </div>

    <%= yield %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, url: pin_path(@pin), method: :patch do |f| %>
  <p>
    <%= image_tag (@pin.photo.url) if @pin.photo? %>
    <%= f.label "Photo" %><br>
    <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.label "Title :" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "Description :" %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit "Enter" %>
  </p>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/pins/index.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "New Pin", new_pin_path %>
        </li>
        <li>
          <%= link_to "User Profile", user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign Out", sign_out_path, method: "delete" %>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Sign Up", sign_up_path %>
        </li>
        <li>
          <%= link_to "Sign In", sign_in_path %>
        </li>
        <li>
          <%= link_to "Sign In with Facebook", "/auth/facebook" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>


<% if current_user %>
<h1 style="margin: 50px auto 40px; text-align:center;">Welcome to Pinteresting, <%= current_user.username %>.</h1>
<% else %>
<h1 style="margin: 50px auto 40px; text-align:center;">Welcome to Pinteresting</h1>
<% end %>

<center>
  <%= link_to "Search", "#", id: "search-link", remote: true %>
</center>

<section id="search-section">
  <div id="search">
    <%= form_tag pins_path, method: :get do %>
    <p>
      <center><%= text_field_tag :query, params[:query], placeholder: "Look for a place" %>
        <%= submit_tag "Search", title: nil, description: nil %></center>
      </p>
      <% end %><br>
  </div>
</section>


<div class="row">
  <div class="col-md-12">
    <div class="transistions-enabled" id="pins" style="margin-left: 60px; margin-right: 60px;">
      <% @pins.each do |pin| %>
      <div class="box panel panel-default" style="width:600px; height:100%; margin-left:5px; margin-right:5px;">
        <%= link_to (image_tag pin.photo), pin %>
        <div class="panel-body">
          <h2>
            <%= link_to pin.title, pin %>
          </h2>
          <p class="user"></p>
          Submitted by:
          <%= pin.user.username %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
$(document).on("click", "#search-link", function(){
  $("#search-section").toggle(700);
});
</script>

app/views/pins/new.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to 'Back', root_path %>
      </li>
    </ul>
  </div>
</nav>

<h1>Create New Pins</h1>

<%= form_for @pin, url: pins_path do |f| %>
  <p>
    <%= image_tag (@pin.photo.url) if @pin.photo? %>
    <%= f.label "Photo" %><br>
    <%= f.file_field :photo %>
  </p>

  <p>
    <%= f.label "Title :" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "Description :" %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit "Enter" %>
  </p>
<% end %>

app/views/pins/show.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "New Pin", new_pin_path %>
      </li>
    </ul>
  </div>
</nav>

<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default" style=" margin-left: auto; margin-right: auto; margin-top: 20px; margin-bottom: 20px;">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.photo %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
        <p>
          Submitted by:
          <%= @pin.user.username %>
        </p>
        <% unless session[:user_id].nil? %>
          <% if @pin.user_id == current_user.id %>
            <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
            <%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>
          <% end %>
          <% unless @pin.user_id == current_user.id %>
          <br>
          <p>
            Like the work? Support the artist now<br>
            <%= link_to "Donate $10", new_pin_donation_path(@pin), class: "btn btn-default" %>
          </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div id="signup-box">
  <%= form_for @user, url: user_path(@user), id: "signup", method: :patch do |f| %>
      <%= image_tag (@user.profpic.url) if @user.profpic? %>
      <%= f.file_field :profpic%>

      <%= f.text_field :username, placeholder: "Username", type: "username", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>
      <%= f.email_field :email, placeholder: "Email", type: "email", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>
      <%= f.password_field :password, placeholder: "Password", type: "password", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>

    <%= f.submit "Enter", class: "inputButton" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Back to User Profile", user_path(current_user) %>
      </li>
    </ul>
  </div>
</nav>

<%= render 'form' %>

app/views/users/new.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Back to Main", root_path %>
      </li>
    </ul>
  </div>
</nav>

<div id="signup-box">
  <%= form_for @user, id: "signup", url: users_path do |f| %>
      <%= image_tag (@user.profpic.url) if @user.profpic? %>
      <%= f.file_field :profpic%>

      <%= f.text_field :username, placeholder: "Username", type: "username", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>
      <%= f.email_field :email, placeholder: "Email", type: "email", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>
      <%= f.password_field :password, placeholder: "Password", type: "password", class: "input pass", style: "border-bottom: 2px solid #ebebeb;" %>

    <%= f.submit "Enter", class: "inputButton" %>
  <% end %>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "Pinteresting", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Back", root_path %>
      </li>
    </ul>
  </div>
</nav>

<h1 id="user-prof">User Profile</h1>

<div class="transistions-enabled" id="pins">
  <div class="box panel panel-default" id="prof-panel" style="width:1000px; height:440px; padding:20px; margin: auto;">
    <div id="prof-pic" style="float:left;" style="width:300px; height:300px;">
      <!-- <% if @fb_user %>
      <%= image_tag(@auth['info']['image'], width: '400', height: '400') %>
      <% else %> -->
      <%= image_tag current_user.profpic %>
      <!-- <% end %> -->
    </div>
    <div class="panel-body pull-left" id="prof-details" style="text-align:left; margin-right: 50px; margin-left:20px;">
      <h2>
        Username: <%= current_user.username %><br>
        <br>
        User email: <%= current_user.email %><br>
      </h2>
      <div class="btn-group pull-left" style="float:left; margin-left:10px;">
        <%= link_to "Edit", edit_user_path, class: "btn btn-default" %>
        <%= link_to "Delete Account", user_path, method: :delete, data: {confirm: "Are you sure you want to delete this user profile?"}, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

<% unless current_user.pins.blank? %>
  <h3 style="text-align:center; margin-top:3%;">Donations</h3>

  <div class="box panel panel-default" id="prof-panel" style="width:1300px; height:100%; padding:20px; margin: auto;">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Pins</th>
          <th>Amount Collected</th>
        </tr>
      </thead>
      <tbody>
        <% current_user.pins.each do |pin| %>
          <tr>
            <td><h4><%= link_to pin.title, pin %></h4></td>
            <td><h4>$ <%= pin.money %></h4></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>